/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package regalairways;

import com.sun.java.accessibility.util.AWTEventMonitor;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Zeyad
 */
public class AddDeleteRoute extends javax.swing.JFrame {
    
Statement statement;
Connection con;
String fromAID;
String toAID;
String fromCode;
String toCode;
//String getToAID="SELECT aID FROM airports WHERE airportCode="+"\""+toCode+"\""+";";
//String getFromAID="SELECT aID FROM airports WHERE airportCode="+"\""+fromCode+"\""+";";
String Distance;
String Fare;
ResultSet rs;
ResultSet rs2;
ResultSet rs3;
ResultSet rs4;
ResultSet rs5;



    /**
     * Creates new form AddDeleteRoute
     */
    public AddDeleteRoute() {
        initComponents();
        
           
              String airCode="SELECT airportCode FROM airports;";
    try {
        con = new Connect().getConnection();
        statement = con.createStatement();
           rs= statement.executeQuery(airCode);
           // get airport codes and populate combo boxes with them
           while(rs.next()){
               fromAirportCombo.addItem(rs.getString(1));
               toAirportCombo.addItem(rs.getString(1));
           }
    } catch (Exception ex) {
        Logger.getLogger(AddDeleteRoute.class.getName()).log(Level.SEVERE, null, ex);
    }
        

       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fromAirportCombo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        toAirportCombo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        distanceTxt = new javax.swing.JTextField();
        fareTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fromAirportCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromAirportComboActionPerformed(evt);
            }
        });

        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        toAirportCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toAirportComboActionPerformed(evt);
            }
        });

        jLabel1.setText("To:");

        jLabel2.setText("From:");

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        jLabel3.setText("Delete Selected Flight");

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        jLabel4.setText("Add Selected Flight");

        jButton2.setText("Add Flight");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        fareTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fareTxtActionPerformed(evt);
            }
        });

        jLabel5.setText("Fare:");

        jLabel6.setText("Distance:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(fromAirportCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(toAirportCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel5))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(distanceTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fareTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(distanceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fareTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fromAirportCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(toAirportCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addGap(44, 44, 44)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fromAirportComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromAirportComboActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_fromAirportComboActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Delete Button Code Here
        
       
        
  
        
        // get selected codes from combo boxes
        fromCode = fromAirportCombo.getSelectedItem().toString();
        toCode = toAirportCombo.getSelectedItem().toString();
        
        
    try {
        // get from airport aid
   
String getFromAID="SELECT aID FROM airports WHERE airportCode="+"\""+fromCode+"\""+";";
        rs2 = statement.executeQuery(getFromAID);
              while(rs2.next()){
                  fromAID = rs2.getString(1);
                  
        }
    } catch (SQLException ex) {
        Logger.getLogger(AddDeleteRoute.class.getName()).log(Level.SEVERE, null, ex);
    }
    try {
        // get to airport aid 
           String getToAID="SELECT aID FROM airports WHERE airportCode="+"\""+toCode+"\""+";";

        rs3 = statement.executeQuery(getToAID);
              while(rs3.next()){
                  toAID = rs3.getString(1);
             
                  
        }
    } catch (SQLException ex) {
        Logger.getLogger(AddDeleteRoute.class.getName()).log(Level.SEVERE, null, ex);
    }
    
      try {
          // delete a route based on from and to aID's
          //check if user selects the same airport
          if (!fromAID.equalsIgnoreCase(toAID)){
           String deleteRoute="DELETE FROM routes where (fromAID = "+fromAID+" and toAID="+toAID+");";
           statement.executeUpdate(deleteRoute);
            JOptionPane.showMessageDialog(null,"Route Succefully Deleted" );
          }
          else{
              JOptionPane.showMessageDialog(null,"From and To airports cannot be the same" ); 
          }
      
    } catch (SQLException ex) {
        Logger.getLogger(AddDeleteRoute.class.getName()).log(Level.SEVERE, null, ex);
         JOptionPane.showMessageDialog(null,"Route does not exist" ); 
    }
    
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void toAirportComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toAirportComboActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_toAirportComboActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //ADD FLIGHT BUTTON CODE HERE
          fromCode = fromAirportCombo.getSelectedItem().toString();
          toCode = toAirportCombo.getSelectedItem().toString();
          Distance = distanceTxt.getText();
          Fare = fareTxt.getText();
        
           try {
        // get from airport aid 
           
        String getFromAID="SELECT aID FROM airports WHERE airportCode="+"\""+fromCode+"\""+";";
        rs4 = statement.executeQuery(getFromAID);
              while(rs4.next()){
                  fromAID = rs4.getString(1);
             
                  
        }
    } catch (SQLException ex) {
        Logger.getLogger(AddDeleteRoute.class.getName()).log(Level.SEVERE, null, ex);
    }
        
         try {
        // get to airport aid 
           String getToAID="SELECT aID FROM airports WHERE airportCode="+"\""+toCode+"\""+";";

        rs5 = statement.executeQuery(getToAID);
              while(rs5.next()){
                  toAID = rs5.getString(1);
             
                  
        }
    } catch (SQLException ex) {
        Logger.getLogger(AddDeleteRoute.class.getName()).log(Level.SEVERE, null, ex);
    }
         
       
    try {
        // execute insert command to add a route to the routes table from the data entered
        // check whether user selected the same from and to airports
        if(!fromAID.equalsIgnoreCase(toAID)){
            String addRoute="INSERT INTO routes (fromAID,toAID,Distance,Price) VALUES ("+fromAID+","+toAID+","+Distance+","+Fare+");"; 
        statement.executeUpdate(addRoute);
        }
        else{
            JOptionPane.showMessageDialog(null,"From and To airports cannot be the same" ); 
        }
         JOptionPane.showMessageDialog(null,"Route Added Successfully" );
    } catch (SQLException ex) {
        Logger.getLogger(AddDeleteRoute.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(null,"Error Adding Route" ); 
    }
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void fareTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fareTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fareTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField distanceTxt;
    private javax.swing.JTextField fareTxt;
    private javax.swing.JComboBox<String> fromAirportCombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> toAirportCombo;
    // End of variables declaration//GEN-END:variables
}
