/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package regalairways;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
public class CancelFlightReservation extends javax.swing.JFrame {

    ResultSet rs;
    Statement statement;
    Connection con;
    String EnteredPhone;
    int cID=0; 
    int frID=0; 
    int bID=0; 
     String name="n/a";
    String date = "n/a";
    
    /**
     * Creates new form CancelFlightReservation
     */
    public CancelFlightReservation() {
        initComponents();
       btnDeleteFlightReservation.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtfldPhoneNumber = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblCustomerName = new javax.swing.JLabel();
        lblFlightDate = new javax.swing.JLabel();
        lblBillTotal = new javax.swing.JLabel();
        btnDeleteFlightReservation = new javax.swing.JButton();
        getFlight = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtfldPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfldPhoneNumberActionPerformed(evt);
            }
        });

        jLabel1.setText("Customer Phone No.");

        jLabel2.setText("Name:");

        jLabel3.setText("Date:");

        jLabel4.setText("Bill:");

        lblCustomerName.setText("         ");

        lblFlightDate.setText("            ");

        lblBillTotal.setText("             ");

        btnDeleteFlightReservation.setText("Delete Flight Reservation");
        btnDeleteFlightReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteFlightReservationActionPerformed(evt);
            }
        });

        getFlight.setText("Get Flight Reservation");
        getFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getFlightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtfldPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblBillTotal)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblCustomerName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblFlightDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addContainerGap(88, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(getFlight)
                    .addComponent(btnDeleteFlightReservation))
                .addGap(122, 122, 122))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfldPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblCustomerName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblFlightDate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblBillTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(getFlight)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeleteFlightReservation)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfldPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfldPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfldPhoneNumberActionPerformed

    private void btnDeleteFlightReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteFlightReservationActionPerformed
        
         String message = "Are you sure you want to cancel "+name+"'s flight?";
         int response = JOptionPane.showConfirmDialog(null, message, "Confirm",
                 JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
             if (response == JOptionPane.YES_OPTION) {
      // YES OPTION CODE
      String DeleteQuery = "DELETE FROM flightreservations WHERE frID ="+frID;
            try {
                statement.executeUpdate(DeleteQuery);
                 JOptionPane.showMessageDialog(null,"Flight was canceled Successfully" );
                 txtfldPhoneNumber.setText("");
                 lblCustomerName.setText(" ");
                  lblFlightDate.setText(" ");
                lblBillTotal.setText(" ");
                btnDeleteFlightReservation.setVisible(false);
                name="n/a";
                date="n/a";
                cID=0;
                frID=0;
                bID=0;
            } catch (SQLException ex) {
                Logger.getLogger(CancelFlightReservation.class.getName()).log(Level.SEVERE, null, ex);
            }
       
    } 
             else{
                  JOptionPane.showMessageDialog(null,"Flight was unable to be canceled" );
             }
    }//GEN-LAST:event_btnDeleteFlightReservationActionPerformed

    private void getFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getFlightActionPerformed

        int flightWay=0; 
        double total=0;
        String getDataCustomer;
        String getDataFlight;
        String getDataBillr;
        EnteredPhone = txtfldPhoneNumber.getText();
          try {
            con = new Connect().getConnection();
            statement = con.createStatement();
            
            // query the database for all customer information
            getDataCustomer="SELECT * FROM customers";
            rs= statement.executeQuery(getDataCustomer);
        } catch (Exception ex) {
            Logger.getLogger(DeleteCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            while(rs.next()){
                if (rs.getString(8).equalsIgnoreCase(EnteredPhone)){
                    //get any information regarding customer here
                   cID= rs.getInt(1);
                   name=rs.getString(2)+" "+rs.getString(3);
                   break;
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(CancelFlightReservation.class.getName()).log(Level.SEVERE, null, ex);
        }
        getDataFlight ="SELECT * FROM flightreservations WHERE cID ="+cID;  
        try {
            rs= statement.executeQuery(getDataFlight);
              while(rs.next()){
                if (rs.getInt(2)==(cID)){
                     //get any information regarding Flight here
                   frID= rs.getInt(1);
                   date=rs.getString(5);
                   flightWay=rs.getInt(9);
                   break;
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(CancelFlightReservation.class.getName()).log(Level.SEVERE, null, ex);
        }
         getDataFlight ="SELECT * FROM bills WHERE frID ="+frID;  
        try {
            rs= statement.executeQuery(getDataFlight);
              while(rs.next()){
                if (rs.getInt(5)==(frID)){
                     //get any information regarding bills here
                   bID= rs.getInt(1);
                   total=rs.getDouble(2);
                   if(flightWay==1)
                   {
                       total=total*2;
                   }
                   break;
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(CancelFlightReservation.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(cID>0)
        {
              if(frID>0)
              {
        lblCustomerName.setText(name);
        lblFlightDate.setText(date);
        lblBillTotal.setText(Double.toString(total));
        btnDeleteFlightReservation.setVisible(true);
              }
                 else
                 {
             JOptionPane.showMessageDialog(null,"Unable to find a flight for that customer" );
                     }       
        }
                else
                 {
             JOptionPane.showMessageDialog(null,"Unable to find customer with that name" );
                    }
    
    }//GEN-LAST:event_getFlightActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteFlightReservation;
    private javax.swing.JButton getFlight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblBillTotal;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblFlightDate;
    private javax.swing.JTextField txtfldPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
